# This workflow will install Python dependencies, and run tests

name: Automated Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Automated Test Suite
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip' # caching pip dependencies
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: Test with pytest
      run: |
        pytest